# Create a new collection point
POST http://localhost:8080/api/collection-points
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlcyI6IltBRE1JTl0iLCJpYXQiOjE3NDQ0NjQxMTAsImV4cCI6MTc0NDU1MDUxMH0.ue-nXAZT6RNBaGzK8LaKIdlf9-svF9FuV7k0SSPqjos
Content-Type: application/json

{
    "name": "Collection Point 4",
    "location": "Location D",
    "milkPurchasePrice": 30.0
}

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    
  "email": "admin@gmail.com",
  "password": "admin123"


}